name: Scraper Automation

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    concurrency:
      group: scraper-automation
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run New Videos Script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python New_vedios.py

      - name: Wait
        run: sleep 1

      - name: Run Old Videos Script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python Old_vedios.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet && exit 0
          git commit -m "auto update scraper data"
          git push
